# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IrfFCRSEAdBKVRz4qdjQqBxDOFbkrasV
"""

from comment_generator_final import *
if __name__ == "__main__":
   cg=Comment_Generator()
   cg.generate_comment("Donald John Trump (born June 14, 1946) is an American politician, media personality, and businessman who served as the 45th president of the United States ")

